config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :availability
  post "select_week", to: "availability#select_week"
  get "select_week", to:  "availability#select_week"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticate :user do
    root "availability#index", as: :authenticated_root
  end
  devise_scope :user do
    root to: "users/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    layout :layout_by_resource

    private
        def layout_by_resource
            if devise_controller?
                "login"
            else
                "application"
            end
        end
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
        end
end

app/controllers/availability_controller.rb
class AvailabilityController < ApplicationController
    def index
    end
    def create
        params[:availability].each do |date|
            if date.present? && date != "0"
                Availability.create(
                    users_id: current_user.id, 
                    start_time: Time.parse(date), 
                    end_time: Time.parse(date) + 1.hour,
                    date_full: DateTime.parse(date),
                    day_number_in_week: Date.parse(date).strftime("%u")
                    )
            end
        end
    end

    def select_week
        @week_selected = params[:data][:week].to_i
        respond_to do |format|
            format.js
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availability_helper.rb
module AvailabilityHelper
    
    def weekend_schedule
        ["10:00 - 11:00","11:00 - 12:00","12:00 - 13:00","13:00 - 14:00","14:00 - 15:00","15:00 - 16:00",
        "16:00 - 17:00","17:00 - 18:00","18:00 - 19:00","19:00 - 20:00", "20:00 - 21:00", "21:00 - 22:00", 
        "22:00 - 23:00", "23:00 - 00:00"]
    end
    
    def week_schedule
        ["19:00 - 20:00", "20:00 - 21:00", "21:00 - 22:00", "22:00 - 23:00", "23:00 - 00:00"]
    end

    def beginning_of_the_week(date)
        (Time.now + ((date.strftime('%V').to_i) * 7).days).beginning_of_week
    end

    def end_of_the_week(date)
        (Time.now + ((date.strftime('%V').to_i) * 7).days).end_of_week
    end

    def get_time_weekend(date, time)
        date += 19.hour + time.hour
    end

    def get_time_week(date, time)
        date += 10.hour + time.hour
    end
end

app/views/availability/_week_availability.html.slim
= form_with(url: availability_index_path, method: :post) do |form|
    - day_of_week = 1
    - start_day = beginning_of_the_week(DateTime.now() + @week_selected.week)
    - 7.times do
        table.table.table-responsive
            thead
                tr
                    th colspan="3"= "#{I18n.l(start_day, format: "%A %d de %B").capitalize}"
                tr
                    th Hora
                    th.text-center ¿Disponible?
            tbody
                - if day_of_week <= 5
                    - hours = week_schedule
                - else
                    - hours = weekend_schedule
                - hour_add = 0
                - hours.each do |shift_hour|
                    tr
                        td= shift_hour
                        td.text-center= form.check_box "availability[]", { class: 'form-check-input', checked: false }, day_of_week <= 5 ? get_time_week(start_day, hour_add) : get_time_weekend(start_day, hour_add)
                    - hour_add += 1
        - day_of_week += 1
        - start_day += 1.day
    = form.submit class:"btn btn-success"

app/views/availability/index.html.slim
.container 
    .row.m-5.p-5
        .col
            h2 Seleccione su disponibilidad
            = form_with(url: select_week_path, method: :post) do |form|
                - i = 1
                - array_weeks = []
                - array_select_weeks= []
                - 10.times do
                    - date_week = DateTime.now() + i.week
                    - array_select_weeks << ["Semana #{date_week.strftime('%V').to_i} de #{date_week.strftime('%Y')} ", date_week.strftime('%V').to_i]
                    - array_weeks << ["#{date_week}"]
                    p.week_lbls style="#{i == 1? '' : 'display:none'}" id="label_week_#{date_week.strftime('%V').to_i}"= p "#{beginning_of_the_week(date_week).strftime('%d/%m/%Y')} -> #{end_of_the_week(date_week).strftime('%d/%m/%Y')}"
                    - i += 1
                    - start_day = beginning_of_the_week(date_week)
                = form.select :week, array_select_weeks,{:include_blank => false}, {:class => "form-select"}
            .p-4#show_schedule

javascript:
    $('#week').change(function() {
        let id_week = $(this).val()
        $(".week_lbls").hide()
        $("#label_week_"+id_week).show()
        $.get('#{select_week_path}', {
            //method: 'GET', (API says default is async/GET)
            //async: true,
            data: { week: $(this).val() }        
        });
    });

app/views/availability/select_week.js.erb
$("#show_schedule").html("<%= j render 'availability/week_availability' %>")

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AppRecorrido
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/shared/topbar" 
    = yield

app/views/layouts/login.slim
doctype html
html
  head
    title
      | AppRecorrido
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  css: 
      html,
      body {
        height: 100%;
      }

      body {
        display: flex;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
      }

      .form-signin .checkbox {
        font-weight: 400;
      }

      .form-signin .form-floating:focus-within {
        z-index: 2;
      }

      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }

      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
  body.text-center
    main.form-signin
      = yield

app/views/layouts/shared/_topbar.html.slim
header.navbar.navbar-dark.sticky-top.bg-dark.flex-md-nowrap.p-0.shadow
  a.navbar-brand.col-md-3.col-lg-2.me-0.px-3 href="#"  App-Monitoreo
  button.navbar-toggler.position-absolute.d-md-none.collapsed aria-controls="sidebarMenu" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#sidebarMenu" data-bs-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  input.form-control.form-control-dark.w-100 aria-label="Search" placeholder="Search" type="text" /
  .navbar-nav
    .nav-item.text-nowrap
      - if user_signed_in?
        span.text-white.px-2= current_user.name 
        = link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "px-2"